### ISSUE TITLE
Can't install/run

### ISSUE THREAD

**Issue by mondras** [traviscrawford/spark-dynamodb#2]
Hey there! Total noob to the whole spark scene so sorry if this is something super obvious. 

I'm trying this on an EMR cluster with spark as instructed with no success. I even tried downloading the repo and running `mvn install` with no success. Any idea of what I'm missing? 

Here's the output:
```
[hadoop@ip-xxxx spark-dynamodb]$ spark-shell --packages com.github.traviscrawford:spark-dynamodb:0.0.1-SNAPSHOT
Ivy Default Cache set to: /home/hadoop/.ivy2/cache
The jars for the packages stored in: /home/hadoop/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/lib/spark-assembly-1.6.1-hadoop2.7.2-amzn-2.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.github.traviscrawford#spark-dynamodb added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
        found com.github.traviscrawford#spark-dynamodb;0.0.1-SNAPSHOT in local-m2-cache
        found com.amazonaws#aws-java-sdk-dynamodb;1.10.68 in local-m2-cache
        found com.amazonaws#aws-java-sdk-s3;1.10.68 in local-m2-cache
        found com.amazonaws#aws-java-sdk-kms;1.10.68 in local-m2-cache
        found com.amazonaws#aws-java-sdk-core;1.10.68 in local-m2-cache
        found commons-logging#commons-logging;1.1.3 in local-m2-cache
        found org.apache.httpcomponents#httpclient;4.3.6 in local-m2-cache
        found org.apache.httpcomponents#httpcore;4.3.3 in local-m2-cache
        found commons-codec#commons-codec;1.6 in local-m2-cache
        found com.fasterxml.jackson.core#jackson-databind;2.5.3 in local-m2-cache
        found com.fasterxml.jackson.core#jackson-annotations;2.5.0 in local-m2-cache
        found com.fasterxml.jackson.core#jackson-core;2.5.3 in local-m2-cache
        found com.fasterxml.jackson.dataformat#jackson-dataformat-cbor;2.5.3 in local-m2-cache
        found joda-time#joda-time;2.8.1 in local-m2-cache
        found com.google.guava#guava;18.0 in local-m2-cache
downloading file:/home/hadoop/.m2/repository/com/github/traviscrawford/spark-dynamodb/0.0.1-SNAPSHOT/spark-dynamodb-0.0.1-SNAPSHOT.jar ...
        [SUCCESSFUL ] com.github.traviscrawford#spark-dynamodb;0.0.1-SNAPSHOT!spark-dynamodb.jar (2ms)
downloading file:/home/hadoop/.m2/repository/com/amazonaws/aws-java-sdk-dynamodb/1.10.68/aws-java-sdk-dynamodb-1.10.68.jar ...
        [SUCCESSFUL ] com.amazonaws#aws-java-sdk-dynamodb;1.10.68!aws-java-sdk-dynamodb.jar (4ms)
downloading file:/home/hadoop/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar ...
        [SUCCESSFUL ] com.google.guava#guava;18.0!guava.jar(bundle) (5ms)
downloading file:/home/hadoop/.m2/repository/com/amazonaws/aws-java-sdk-s3/1.10.68/aws-java-sdk-s3-1.10.68.jar ...
        [SUCCESSFUL ] com.amazonaws#aws-java-sdk-s3;1.10.68!aws-java-sdk-s3.jar (3ms)
downloading file:/home/hadoop/.m2/repository/com/amazonaws/aws-java-sdk-core/1.10.68/aws-java-sdk-core-1.10.68.jar ...
        [SUCCESSFUL ] com.amazonaws#aws-java-sdk-core;1.10.68!aws-java-sdk-core.jar (3ms)
downloading file:/home/hadoop/.m2/repository/com/amazonaws/aws-java-sdk-kms/1.10.68/aws-java-sdk-kms-1.10.68.jar ...
        [SUCCESSFUL ] com.amazonaws#aws-java-sdk-kms;1.10.68!aws-java-sdk-kms.jar (2ms)
downloading file:/home/hadoop/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
        [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (1ms)
downloading file:/home/hadoop/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar ...
        [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.3.6!httpclient.jar (2ms)
downloading file:/home/hadoop/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar ...
        [SUCCESSFUL ] com.fasterxml.jackson.dataformat#jackson-dataformat-cbor;2.5.3!jackson-dataformat-cbor.jar(bundle) (1ms)
downloading file:/home/hadoop/.m2/repository/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar ...
        [SUCCESSFUL ] joda-time#joda-time;2.8.1!joda-time.jar (3ms)
downloading file:/home/hadoop/.m2/repository/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar ...
        [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.3.3!httpcore.jar (3ms)
:: resolution report :: resolve 6570ms :: artifacts dl 62ms
        :: modules in use:
        com.amazonaws#aws-java-sdk-core;1.10.68 from local-m2-cache in [default]
        com.amazonaws#aws-java-sdk-dynamodb;1.10.68 from local-m2-cache in [default]
        com.amazonaws#aws-java-sdk-kms;1.10.68 from local-m2-cache in [default]
        com.amazonaws#aws-java-sdk-s3;1.10.68 from local-m2-cache in [default]
        com.fasterxml.jackson.core#jackson-annotations;2.5.0 from local-m2-cache in [default]
        com.fasterxml.jackson.core#jackson-core;2.5.3 from local-m2-cache in [default]
        com.fasterxml.jackson.core#jackson-databind;2.5.3 from local-m2-cache in [default]
        com.fasterxml.jackson.dataformat#jackson-dataformat-cbor;2.5.3 from local-m2-cache in [default]
        com.github.traviscrawford#spark-dynamodb;0.0.1-SNAPSHOT from local-m2-cache in [default]
       com.google.guava#guava;18.0 from local-m2-cache in [default]
        commons-codec#commons-codec;1.6 from local-m2-cache in [default]
        commons-logging#commons-logging;1.1.3 from local-m2-cache in [default]
        joda-time#joda-time;2.8.1 from local-m2-cache in [default]
        org.apache.httpcomponents#httpclient;4.3.6 from local-m2-cache in [default]
        org.apache.httpcomponents#httpcore;4.3.3 from local-m2-cache in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   15  |   15  |   15  |   0   ||   15  |   11  |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                [NOT FOUND  ] com.fasterxml.jackson.core#jackson-databind;2.5.3!jackson-databind.jar(bundle) (0ms)

        ==== local-m2-cache: tried

          file:/home/hadoop/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.jar

                [NOT FOUND  ] commons-codec#commons-codec;1.6!commons-codec.jar (0ms)

        ==== local-m2-cache: tried

          file:/home/hadoop/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar

                [NOT FOUND  ] com.fasterxml.jackson.core#jackson-annotations;2.5.0!jackson-annotations.jar(bundle) (0ms)

        ==== local-m2-cache: tried

          file:/home/hadoop/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.0/jackson-annotations-2.5.0.jar

                [NOT FOUND  ] com.fasterxml.jackson.core#jackson-core;2.5.3!jackson-core.jar(bundle) (0ms)

        ==== local-m2-cache: tried

          file:/home/hadoop/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::              FAILED DOWNLOADS            ::

                :: ^ see resolution messages for details  ^ ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: commons-codec#commons-codec;1.6!commons-codec.jar

                :: com.fasterxml.jackson.core#jackson-databind;2.5.3!jackson-databind.jar(bundle)

                :: com.fasterxml.jackson.core#jackson-annotations;2.5.0!jackson-annotations.jar(bundle)

                :: com.fasterxml.jackson.core#jackson-core;2.5.3!jackson-core.jar(bundle)

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: commons-codec#commons-codec;1.6!commons-codec.jar, download failed: com.fasterxml.jackson.core#jackson-databind;2.5.3!jackson-databind.jar(bundle), download failed: com.fasterxml.jackson.core#jackson-annotations;2.5.0!jackson-annotations.jar(bun
dle), download failed: com.fasterxml.jackson.core#jackson-core;2.5.3!jackson-core.jar(bundle)]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1068)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:287)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:154)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by BreachSim** [comment]
I got it working by following the instructions below.

clone the repo.
build the package using: mvn install -DskipTests 
(I skipped the tests because i couldn't get them to pass since it requires a local version of DynamoDb)
then instead of spark-shell --packages ... I used spark-shell --jars [path to built jar]
In the shell I imported : import com.github.traviscrawford.spark._ and import com.github.traviscrawford.spark.dynamodb._

**Comment by shweta-sah** [comment]
Thanks @traviscrawford  for this amazing package.

@BreachSim  Thank you for the instructions, I followed them and then read a table from DynamoDB from the default region
` val Yelpdf = sqlContext.read.dynamodb("YelpSmall")`

but it seems only the schema was read and not the data because when I run `Yelpdf.show()` , it does tell m the number of items in the DynamoDB table but shows a blank data frame with header names.
What am I doing wrong here?

Here is the output:
`
scala> Yelpdf.show()
16/07/21 14:58:58 INFO DynamoDBRelation: Table YelpSmall contains 3 items using 2437 bytes.
16/07/21 14:58:58 INFO DynamoDBRelation: Schema for tableName YelpSmall: StructType(StructField(business.id,StringType,true), StructField(date,StringType,true), StructField(review_id,StringType,true), StructField(stars,LongType,true), StructField(text,StringType,true), StructField(type,StringType,true), StructField(user_id,StringType,true), StructField(votes,StructType(StructField(cool,LongType,true), StructField(funny,LongType,true), StructField(useful,LongType,true)),true))
16/07/21 14:58:58 INFO SparkContext: Starting job: show at <console>:34
16/07/21 14:58:58 INFO DAGScheduler: Got job 5 (show at <console>:34) with 1 output partitions
16/07/21 14:58:58 INFO DAGScheduler: Final stage: ResultStage 8 (show at <console>:34)
16/07/21 14:58:58 INFO DAGScheduler: Parents of final stage: List()
16/07/21 14:58:58 INFO DAGScheduler: Missing parents: List()
16/07/21 14:58:58 INFO DAGScheduler: Submitting ResultStage 8 (MapPartitionsRDD[29] at show at <console>:34), which has no missing parents
16/07/21 14:58:58 INFO MemoryStore: Block broadcast_8 stored as values in memory (estimated size 3.4 KB, free 49.2 KB)
16/07/21 14:58:58 INFO MemoryStore: Block broadcast_8_piece0 stored as bytes in memory (estimated size 2019.0 B, free 51.2 KB)
16/07/21 14:58:58 INFO BlockManagerInfo: Added broadcast_8_piece0 in memory on 172.31.2.110:36003 (size: 2019.0 B, free: 518.0 MB)
16/07/21 14:58:58 INFO SparkContext: Created broadcast 8 from broadcast at DAGScheduler.scala:1006
16/07/21 14:58:58 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 8 (MapPartitionsRDD[29] at show at <console>:34)
16/07/21 14:58:58 INFO YarnScheduler: Adding task set 8.0 with 1 tasks
16/07/21 14:58:58 INFO TaskSetManager: Starting task 0.0 in stage 8.0 (TID 62, ip-172-31-2-110.ec2.internal, partition 0,PROCESS_LOCAL, 3634 bytes)
16/07/21 14:58:58 INFO BlockManagerInfo: Added broadcast_8_piece0 in memory on ip-172-31-2-110.ec2.internal:35135 (size: 2019.0 B, free: 6.5 GB)
16/07/21 14:58:58 INFO TaskSetManager: Finished task 0.0 in stage 8.0 (TID 62) in 81 ms on ip-172-31-2-110.ec2.internal (1/1)
16/07/21 14:58:58 INFO DAGScheduler: ResultStage 8 (show at <console>:34) finished in 0.081 s
16/07/21 14:58:58 INFO YarnScheduler: Removed TaskSet 8.0, whose tasks have all completed, from pool
16/07/21 14:58:58 INFO DAGScheduler: Job 5 finished: show at <console>:34, took 0.088647 s
+-----------+----+---------+-----+----+----+-------+-----+
|business.id|date|review_id|stars|text|type|user_id|votes|
+-----------+----+---------+-----+----+----+-------+-----+
+-----------+----+---------+-----+----+----+-------+-----+
`

**Comment by BreachSim** [comment]
@shweta-sah
I don't know why this is happening but for the sake of it, can you try to do:
Yelpdf.select("business.id").show    assuming business.id is your key on the dynamo table.

I found that if all keys are not included in the query it fails to retreive the data. 
Also here's the imports that I use.

import com.github.traviscrawford.spark._
import com.github.traviscrawford.spark.dynamodb._
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient
import com.amazonaws.services.dynamodbv2.document.DynamoDB
import com.amazonaws.services.dynamodbv2.document.Item
import com.amazonaws.services.dynamodbv2.model._
import org.apache.spark._
import org.apache.spark.sql._
import org.apache.spark.sql.types._
import scala.collection.JavaConversions._

**Comment by shweta-sah** [comment]
@BreachSim Thank you.  I used the above imports and everything except business.id was imported. I realised that it was the period in `business.id` that was probably messing things up and so when I changed it to `business_id`, Yelpdf.show() showed me the data.

Although, when I try querying it furthermore, only `Yelpdf.orderBy("date").show` worked.
1) `Yelpdf.select(review_id).show` or a select query on any column gave me null values as follows:
Note: `review_id` is the primary key.
+---------+
|review_id|
+---------+
|     null     |
|     null     |
|     null     |
+---------+

2)Yelpdf.groupBy("business_id").agg(avg("stars").alias("avg_stars")).sort(desc("avg_stars")).show()
+--------------------+---------+
|         business_id|avg_stars|
+--------------------+---------+
|PkfrnyElc26gPUghV...|     null|
|SgTjnyElc26gPUghV...|     null|
+--------------------+---------+

3)Yelpdf.filter(length(Yelpdf("text"))>30).groupBy("business_id").agg(avg("stars").alias("avg_stars")).sort(desc("avg_stars")).show()
+-----------+---------+
|business_id|avg_stars|
+-----------+---------+
+-----------+---------+

Also, I tried creating the temptable to directly run SQL, but I got the same results.

**Comment by BreachSim** [comment]
@shweta-sah 
Glad I could help.
Im still a newbie with dynamodb but like I said I think that all column that is part of primary and sort keys need to be included in the first query. I think this is a dynamodb/nosql "limitation". But as I said Im still new to the world of nosql databases.

So what I do in my project is that I do a first query containing all columns and then cache it:
i.e: val Yelpdf = sqlContext.read.dynamodb("YelpSmall").cache

For me it works because there is not that many rows in my table yet. 

then if you do Yelpdf.select("avg_stars").show it should work because all the data were previously mounted in me memory.

**Comment by traviscrawford** [comment]
Hi @shweta-sah and @BreachSim - super excited to see you're getting benefit from this :)

Above there was a question about the following statements showing the table schema, but no rows:

```
val Yelpdf = sqlContext.read.dynamodb("YelpSmall")
Yelpdf.printSchema()
Yelpdf.show()
```

I believe this is the correct behavior because nothing was selected to populate the DataFrame. The confusion about why the data frame has no rows probably comes from the log output that shows the DynamoDB table is being scanned.

That confusion probably comes from https://github.com/traviscrawford/spark-dynamodb/blob/master/src/main/scala/com/github/traviscrawford/spark/dynamodb/DynamoDBRelation.scala#L55 where we scan a page of results from the DynamoDB table to infer it's schema. DynamoDB tables only have hash/range keys as their prescribed schema. Beyond that, every record can have it's own schema. For that reason, users can either provide the table schema to this scanner, or the schema can be inferred from a sample of actual records.

Does that make sense? Please let me know if there's something we could do to make this more clear, either in the docs or logging output.

**Comment by traviscrawford** [comment]
Above there was also a question about selecting data from the table. My recommendation is running a SQL statement to select rows in the table, making sure to cache the results if you plan to run multiple statements against the output. For example:

```
val Yelpdf = sqlContext.read.dynamodb("YelpSmall")
Yelpdf.registerTempTable("yelp")
val data = sqlContext.sql("select * from yelp").cache
```

If you'd like to project out specific columns, the scanner will only fetch those values from your DynamoDB table because the [PrunedScan](https://github.com/apache/spark/blob/4cbf611c1dc88111ff49d005e902ad5864799ede/sql/core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala#L240) interface is implemented. We do not implement [PrunedFilteredScan](https://github.com/apache/spark/blob/4cbf611c1dc88111ff49d005e902ad5864799ede/sql/core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala#L252) at this time, so your filters will not be pushed into the table scan. That is, you'll always do a full table scan when querying your DynamoDB table, so be sure to cache the results, or perhaps write the output to HDFS/S3 and read if from there as needed.

**Comment by BreachSim** [comment]
@traviscrawford Thanks for the update travis! Are you planning to implement PrunedFilterScanned in a foreseeable future? Dynamodb tables tends to be pretty big , having full table scan on the first read takes a lot of time.

**Comment by mondras** [comment]
@BreachSim a bit late but thanks for the help man! It worked like a charm.

**Comment by traviscrawford** [comment]
I'm not currently planning on implementing filter support, since my use-case is exporting full tables to Redshift so I don't need filters. It's definitely something that would be a great addition, and something is like to eventually add, but no current plans.

**Comment by findchris** [comment]
Anyone get this working correctly with `sbt`?

I added this dependency:
```scala
"com.github.traviscrawford" %% "spark-dynamodb" % "0.0.2"
```
And get this on `sbt assembly`:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.traviscrawford#spark-dynamodb_2.10;0.0.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

Thanks for any help.

**Comment by findchris** [comment]
@BreachSim Some pruning support that might be extracted into a pull request, fwiw:  https://github.com/cfregly/spark-dynamodb/blob/master/main/scala/com/databricks/spark/dynamodb/DynamoDBRelation.scala

**Comment by timchan-lumoslabs** [comment]
@findchris Have you tried
```scala
"com.github.traviscrawford" % "spark-dynamodb" % "0.0.2"
```
Yours has an extra `%`.

**Comment by BreachSim** [comment]
@findchris Thanks for the pointer I will have a look at it.

**Comment by BreachSim** [comment]
@findchris Regarding your issue. I was not able to make it work using sbt of maven. What I do is I clone the repo on the driver machine, compile it and then use it with the --jar option of spark.

**Comment by findchris** [comment]
@timchan-lumoslabs - Thanks for the tip.  `sbt assembly` succeeds now (cc/ @BreachSim).  I do have some `libraryDependencies` in my `build.sbt` that have `%%` in their definitions, so I'll need to research the difference.

**Comment by traviscrawford** [comment]
Are the issues using this from an sbt project because it's not published for a specific Scala version? I typically use http://www.pantsbuild.org for my Scala projects and have not used sbt, which its my understanding does support publishing Scala version-specific packages. I'm happy to switch over to sbt if that's helpful for folks. Anyone know of a simple example project that publishes to maven central I could learn from?
